# Make file for C++ with variables
# Jakapop Khongnawang 5/2/2023
CXX=g++
CXXFLAGS= -std=c++11 -g -Wall -Wshadow -Wpedantic -Wvla -Werror
# add some standard arguments to gcc
# -std=c99 means to use the C99 version of the C language.
# -g means to enable gdb by storing information such as your variable names
#   in the executable
#  -Wall, -Wshadow, -Wpedantic, Wvla, -Werror turn on extra warnings to let
#   you know about anomolies in your code might indicate a bug.
SOURCES=a26_jakapop.cpp 
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=a26_jakapop

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ 
#add -lm after @ to include c math library

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)

.c.o:
	$(CXX) $(CXXFLAGS) -c -o $@ $<